.github/bors.toml, .github/workflows/bors-commit-lint.yml
Bors seems to be having trouble checking the PR status
and making sure the PR title is a conventional commit message.
This changes it so that bors ignores the PR status,
but runs a check on the generated commit,
making sure that it matches the conventional commit specification.
=> chore: change strategy for bors commit message linting

Cargo.lock, crates/bones_bevy_asset/CHANGELOG.md, crates/bones_bevy_asset/Cargo.toml, crates/bones_bevy_asset/macros/CHANGELOG.md, crates/bones_bevy_asset/macros/Cargo.toml, crates/bones_bevy_renderer/CHANGELOG.md, crates/bones_bevy_renderer/Cargo.toml, crates/bones_matchmaker/CHANGELOG.md, crates/bones_matchmaker/Cargo.toml, crates/bones_matchmaker_proto/CHANGELOG.md, crates/quinn_runtime_bevy/CHANGELOG.md
Unfortunately, we have a git dependency on `bevy_smiple_tilemap` which broke the automated release of that crate.
Also, trying to release it again, ended up bumping `bones_bevy_asset_macros` to v0.2.0. :/ Not that big a deal I guess.
=> Release `bones_matchmaker` and `bones_bevy_asset`.

crates/bones_ecs/src/entities.rs
This is important for use cases where you need to manually
serialize/load an entity ID.
=> feat(bones_ecs): make `Entity::new()` public. (#93)

crates/bones_matchmaker/src/lib.rs
This used to be used, but isn't applicable anymore.
=> style: remove unnecessary set of `BLOCKING_MAX_THREADS` ENV var.

Dockerfile
The previous commit accidentally left the custom CA certificate code in the dockerfile.
=> fix(docker): comment out the custom CA certificate in the Dockerfile.

Cargo.lock, crates/bones_bevy_renderer/Cargo.toml
This fixes https://github.com/fishfolk/jumpy/issues/841, can switch back to original crate once fix is merged upstream of fork.
Change we are introducing is here: https://github.com/forbjok/bevy_simple_tilemap/compare/master...MaxCWhitehead:bevy_simple_tilemap:v0.11.0
Gates rayon behind feature flag, which we do not use.
=> fix(perf): Use fork of bevy_simple_tilemap with rayon par_iter feature disabled until PR merged.

framework_crates/bones_ecs/src/components.rs
This was already fixed in #132.
=> docs: remove old TODO comment re two-step component borrow.

framework_crates/bones_asset/examples/tutorial.rs, framework_crates/bones_ecs/src/components/iterator.rs, framework_crates/bones_ecs/src/entities.rs, framework_crates/bones_ecs/src/stage.rs, framework_crates/bones_ecs/src/system.rs, framework_crates/bones_ecs/src/world.rs, framework_crates/bones_framework/src/animation.rs, framework_crates/bones_framework/src/camera.rs, framework_crates/bones_framework/src/input/keyboard.rs, framework_crates/bones_framework/src/input/mouse.rs, framework_crates/bones_framework/src/input/time.rs, framework_crates/bones_framework/src/input/time/timer.rs, framework_crates/bones_framework/src/localization.rs, framework_crates/bones_framework/src/render/audio.rs, framework_crates/bones_framework/src/render/camera.rs, framework_crates/bones_framework/src/render/color.rs, framework_crates/bones_framework/src/render/line.rs, framework_crates/bones_framework/src/render/sprite.rs, framework_crates/bones_framework/src/render/tilemap.rs, framework_crates/bones_framework/src/render/ui.rs, framework_crates/bones_lib/src/lib.rs, framework_crates/bones_schema/examples/custom_type_data.rs, framework_crates/bones_schema/macros/src/lib.rs, framework_crates/bones_schema/src/ptr.rs, framework_crates/bones_schema/src/schema.rs, framework_crates/bones_schema/tests/tests.rs
This makes it much more convenient to derive HasSchema for types that don't need to support scripting or be `#[repr(C)]`.
=> feat: make `HasSchema` assume `#[schema(opaque)]` if `#[repr(C)]` is not specified.

Cargo.lock, demos/features/assets/locales/en-US/menu.ftl, demos/features/src/main.rs, framework_crates/bones_bevy_renderer/Cargo.toml, framework_crates/bones_bevy_renderer/src/lib.rs, framework_crates/bones_framework/Cargo.toml, framework_crates/bones_framework/src/lib.rs, framework_crates/bones_framework/src/storage.rs, framework_crates/bones_lib/Cargo.toml, framework_crates/bones_schema/macros/src/lib.rs, framework_crates/bones_schema/src/registry.rs, framework_crates/bones_schema/src/ser_de.rs
There is a lot that should be improved on, but it is usable for now.
=> feat: implement initial persisted storage API.

framework_crates/bones_asset/src/server.rs, framework_crates/bones_schema/src/ser_de.rs
Also removes a `visit_str()` implementation from the asset server that shouldn't be necessary.
=> fix: fix schema serializer and deserializer for some.

framework_crates/bones_framework/src/render/ui.rs
In other words, `impl From<FontMeta> for egui::FontSelection`.
=> feat: make it possible to pass `FontMeta` directly to egui methods expecting fonts.

demos/assets_minimal/src/main.rs, demos/features/src/main.rs, demos/hello_world/src/main.rs, framework_crates/bones_framework/src/render/ui.rs
The `Egui` system param didn't make things much easier and it meant that there was two ways to do something when there should be one clear option.
=> refactor!: remove `Egui` system parameter in favor of using `&World` directly.

framework_crates/bones_framework/src/render/ui/widgets/bordered_button.rs, framework_crates/bones_framework/src/render/ui/widgets/bordered_frame.rs
This makes it a little more ergonomic to use bordered buttons and styles with margins from metadata.
=> feat!: allow taking `MarginMeta` directly for bordered panels and buttons.

Cargo.lock, framework_crates/bones_asset/src/asset.rs, framework_crates/bones_asset/src/handle.rs, framework_crates/bones_asset/src/io.rs, framework_crates/bones_asset/src/server.rs, framework_crates/bones_bevy_renderer/src/lib.rs
Previously assets would get mixed up if they had the same file contents, because the Cid that was used to index them in asset storage would be the same. Now se update the Cid to include the contents of the file, the full name of the schema used to load it, and the Cids of the dependencies.
=> fix: fix asset mixup when two asset files have the same contents in different locations.

demos/features/src/main.rs, framework_crates/bones_framework/src/render/audio.rs
We had put the audio manager in an `Arc<AtomicCell<T>>` so that it could be `Clone`, but that was unnecessary when it is a shared resource that will not be duplicated in network play.
=> feat: make audio manager easier to to access and remove extra atomic cell.

framework_crates/bones_asset/src/io.rs
Some web servers handle paths a little different. This makes sure that paths are relative to the asset root before loading them, which should fix any issues.
=> fix: fix WASM asset loading path handling for some web servers.

framework_crates/bones_bevy_renderer/src/lib.rs
In https://github.com/fishfolk/jumpy/issues/861 it appears that the assets may have finished loading after the input system, but before the update system, leading to the game being ticked without the keyboard inputs.
This initializes all of the input resources to their defaults so that the game will never be ticked without them.
=> fix: make sure input resources are always present.

framework_crates/bones_framework/src/time/stopwatch.rs, framework_crates/bones_framework/src/time/timer.rs
It isn't super critical that we test the timers and it is costing us lots of time in CI, so we disable the doc tests and we make some tests only run on miri, where time is faked and the tests complet quickly.
=> test: ignore doc tests for timers to reduce CI time.

demos/assets_minimal/src/main.rs, demos/features/src/main.rs, framework_crates/bones_asset/examples/tutorial.rs, framework_crates/bones_framework/src/lib.rs, framework_crates/bones_framework/src/render/audio.rs, framework_crates/bones_schema/src/schema.rs
This adds a `#[must_use]` attribute to `schema()` and adds a new `register_schema()` method so that it is more apparent what is happening when you make a free-standing schema() call to force it to register the schema.
=> feat: add a new `register_schema()` type method to make intent more clear.

demos/scripting/assets/demo-data.yaml, demos/scripting/assets/game.yaml, demos/scripting/assets/pack.yaml, demos/scripting/assets/plugin1.plugin.lua, demos/scripting/assets/schemas/ScriptingDemoData.yaml, demos/scripting/src/main.rs, framework_crates/bones_asset/src/asset.rs, framework_crates/bones_asset/src/handle.rs, framework_crates/bones_asset/src/server/schema_loader.rs, framework_crates/bones_schema/src/ptr.rs, framework_crates/bones_schema/src/std_impls.rs, framework_crates/bones_scripting/src/lib.rs, framework_crates/bones_scripting/src/lua/bindings/ecsref.rs
Updates the scripting example to show how you can define new metadata asset types and access the data in scripts.
This also allows lua to assign an untyped handle to a typed handle and vice-versa without complaining.
=> feat: allow using runtime schemas as metadata assets.

demos/scripting/src/main.rs, framework_crates/bones_framework/src/render/sprite.rs, framework_crates/bones_scripting/src/lua.rs, framework_crates/bones_scripting/src/lua/bindings.rs, framework_crates/bones_scripting/src/lua/bindings/components.rs, framework_crates/bones_scripting/src/lua/bindings/ecsref.rs, framework_crates/bones_scripting/src/lua/bindings/entities.rs, framework_crates/bones_scripting/src/lua/bindings/schema.rs
- add an `eq` function for comparing schemas in lua
- add a `schema_of` function to get the schema of a value in lua
- add a `schema:without()` function to power the ability to exclude components from `entities:iter_with()`
- allow assigning lua and rust strings to `Ustr` refs
=> feat: add misc. scripting updates needed for Jumpy.

framework_crates/bones_asset/examples/tutorial.rs, framework_crates/bones_asset/src/server.rs, framework_crates/bones_bevy_renderer/src/lib.rs
This allows you to prefix `core:` or `assetpack_id:` to an asset path to load the asset from another asset pack.
=> feat: allow asset packs to load assets from other asset packs.

framework_crates/bones_ecs/src/resources.rs, framework_crates/bones_lib/src/lib.rs
This change makes sure that shared resources are shared across snapshots instead of having their contents duplicated when a world is cloned.
It also makes `Entities` a non-shared resource, so that worlds can have their entities snapshotted properly.
=> fix!: fix the way resources are handled in snapshots.

Cargo.lock, framework_crates/bones_bevy_renderer/src/lib.rs
Due to the random system ordering in Bevy and the fact that I overlooked that the input collection system runs in `PreUpdate`, inputs would sometimes not get sent to bones, or they would be delayed by a frame.
Adding an explicit ordering constraint on the bones input system fixes this.
=> fix(bones_bevy_renderer): fix inputs being missed or delayed.

framework_crates/bones_asset/src/server.rs
Simple fix for asset dependencies not being sorted correctly, fixes not having a reliable cid for asset handle replication.
Fixes #285 (though we may consider a better solution in the future as this requires two loops to gather / sort cids).
=> fix(assets): Sort asset dependency cids before updating parent cid

framework_crates/bones_framework/src/input/mouse.rs
Just adds a couple missing derives on `MouseButton` to make it a bit easier to work with (`KeyCode` already has them)
=> fix: add missing PartialEq/Eq/Hash derive for MouseButton

framework_crates/bones_schema/src/ptr.rs
tldr: the code inside bool::then_some is always executed, but the code in the closure from bool::then is only executed if is true.
This is UB, because the bool::then_some is a function that takes a bool and a generic value, because of that, the value inside of it is always evaluated, independent if the bool is true/false.
it's clear if the desugarize the syntax:
```rust
// first we get the true/false for the condition
let cond: bool = matches!(self.schema.kind, SchemaKind::Vec(_));
// then we evaluate the expression to pass the value as parameter
// UB here, the is executed always, independent of the cond being true/false
let value = unsafe { self.cast_into_unchecked::<SchemaMap>() };
// then we call the function `bool::then_some`.
bool::then_some(cond, value)
```
The solution is simply …
=> fix: undefined behaviour with then_some

framework_crates/bones_asset/src/cid.rs, framework_crates/bones_asset/src/handle.rs, framework_crates/bones_asset/src/lib.rs, framework_crates/bones_asset/src/network_handle.rs, framework_crates/bones_asset/src/server.rs
Add NetworkHandle to replicate asset handles using content id.
=> feat(assets): Add NetworkHandle type to replicate asset handles

Cargo.lock, framework_crates/bones_framework/Cargo.toml, framework_crates/bones_framework/src/input.rs, framework_crates/bones_framework/src/lib.rs, framework_crates/bones_framework/src/networking.md, framework_crates/bones_framework/src/networking.rs, framework_crates/bones_framework/src/networking/certs.rs, framework_crates/bones_framework/src/networking/input.rs, framework_crates/bones_framework/src/networking/lan.rs, framework_crates/bones_framework/src/networking/online.md, framework_crates/bones_framework/src/networking/online.rs, framework_crates/bones_framework/src/networking/proto.rs, framework_crates/bones_framework/src/utils.rs
This is the bones half of getting networking back in.
Most things haven't changed much here, though I did define a number of input traits, for collecting / managing input. I tried to not have a million generic type params everywhere, used a lot of associated types, but unsure if this ended up being better or worse, as got a little hairy in spots.
Handling player disconnects is TODO. (not sure how we used to handle this, will look).
=> feat(networking): Port networking to bones

framework_crates/bones_framework/src/render/color.rs
Uses sRGB conversion instead of linear conversion.
This fixes the display of UI colors specified in Jumpy style assets.
=> fix: fix conversion of bones `Color` to `egui::Color32`.

Cargo.lock, framework_crates/bones_ecs/Cargo.toml, framework_crates/bones_framework/Cargo.toml, framework_crates/bones_schema/Cargo.toml, framework_crates/bones_scripting/Cargo.toml
This gets rid of our last git dependency, allowing us to finally make another crates.io release! 🚀
=> build: update to released version of Kira.

framework_crates/bones_framework/src/networking.rs
This fixes non-running sessions (borrowed from Game) being lost during net rollback, as they are cloned empty. Fixes #336
=> fix: preserve sessions when loading world snapshot in networking.

Cargo.lock, framework_crates/bones_framework/Cargo.toml, framework_crates/bones_framework/src/networking.rs, framework_crates/bones_framework/src/networking/debug.rs
Add network debug menu back into bones. The session plugin is not installed by bones, optionally may be installed in game by user.
Closes #301
=> feat(network-diagnostics): Add network debug egui window to bones

framework_crates/bones_bevy_renderer/src/lib.rs, framework_crates/bones_ecs/src/components/iterator.rs, framework_crates/bones_ecs/src/components/typed.rs, framework_crates/bones_ecs/src/components/untyped.rs, framework_crates/bones_ecs/src/entities.rs
Adds an Optional type that can be built from Comp / CompMut to optionally retrieve components in entities.iter_with without filtering by them.
I split some of the iter bitset functions out of ComponentStore into ComponentIterBitset Trait, so that generic type in Optional can implement trait bounds and expose these for its QueryItems implementations. See doc comment or test for usage.
Resolves #340
=> feat(optional_queries): Allow entities.iter_with to optionally retrieve components without filtering on them. (#340)

framework_crates/bones_framework/src/networking/proto.rs
In Jumpy am adding an additional input for ragdoll'ing self and this pushed us over 16 bits in input bitfield.
This change allows us to build `DenseMoveDirection` from a u32, otherwise the bitfield `DensePlayerControl` (in Jumpy) fails to compile.
Only the 12 least significant bits are used in DenseMoveDirection, so casting u32 -> u16 should not impact anything here.
=> fix(input): Support DenseMoveDirection from u32

framework_crates/bones_framework/src/debug.rs
Make Res<FrameDiagState> optional in window system, otherwise it may be accessed during race before it is initialized as shared resourcein bones_bevy_renderer.
=> fix: Fix crash in frame time diagnostics window system

framework_crates/bones_ecs/src/bitset.rs
Fix an error cause by compiling with all features: `cargo build --all-features`.
Make the conditional compilation on the `const BITSET_EXP` declarations mutually exclusive so that any combination of the `keysize*` features only ever results in a single instance.
Note that the `keysize16` declaration does not exclude all other keysizes since it is the default. If multiple keysize features are enabled, including 16, then the declaration for `keysize16` will be the only one. If multiple keysize features are enabled, not including 16, then there will be no declarations, causing a compile error. This is fine since users should only enable one of these features at a time.
```
error[E0428]: the name `BITSET_EXP` is defined multiple times
--> framework_crates/bones_ecs/src/bitset.rs:18:1
|
16 | …
```
=> fix: compiling with all features

Cargo.lock, framework_crates/bones_ecs/Cargo.toml, framework_crates/bones_ecs/macros/Cargo.toml, framework_crates/bones_ecs/macros/core/Cargo.toml, framework_crates/bones_ecs/macros/core/src/lib.rs, framework_crates/bones_ecs/macros/src/lib.rs, framework_crates/bones_ecs/src/lib.rs
Closes #16 
Add a procedural derive macro to generate an `impl SystemParam` for structs.
Allows jumpy to replace this:
```rust
impl_system_param! {
struct MySystemParam<'a> {
commands: Commands<'a>,
entities: ResMut<'a, Entities>,
}
}
```
with this:
```rust
#[derive(SystemParam)]
struct MySystemParam<'a> {
commands: Commands<'a>,
entities: ResMut<'a, Entities>,
}
```
=> feat: add `SystemParam` derive macro

Cargo.lock, deny.toml, framework_crates/bones_asset/Cargo.toml, framework_crates/bones_asset/examples/tutorial.rs, framework_crates/bones_bevy_renderer/Cargo.toml, framework_crates/bones_bevy_renderer/src/lib.rs, framework_crates/bones_framework/Cargo.toml, framework_crates/bones_framework/src/render/sprite.rs, framework_crates/bones_framework/src/render/ui.rs, framework_crates/bones_framework/src/render/ui/widgets/bordered_button.rs, framework_crates/bones_framework/src/render/ui/widgets/bordered_frame.rs, framework_crates/bones_scripting/Cargo.toml, framework_crates/bones_scripting/src/lua.rs, other_crates/bones_matchmaker/Cargo.toml, other_crates/bones_matchmaker/examples/matchmaker_client.rs, other_crates/bones_matchmaker/src/cli.rs, other_crates/quinn_runtime_bevy/Cargo.toml, other_crates/type_ulid/src/lib.rs
- Downgrade bevy to 0.11
- Changes to `bevy_sprite` make the upgrade too complicated to do at the moment
- Upgrade `bitfield-rle` to `0.2.1`
- Fixes the CI advisory errors for the `failure` crate
=> fix: downgrade bevy to 0.11

framework_crates/bones_bevy_renderer/src/lib.rs
Speculative fix for #377 (see for context)
It seems both the `setup_egui` and `step_bones_game` systems are gated by if assets are loaded, which is an async process. My theory is that assets finish loading after PreUpdate, before Update, so bones steps without EguiCtx.
This prevents `step_bones_game` from being run until EguiCtx is inserted in `setup_egui`. ~~Becaues `setup_egui` is gated by assets loaded, `step_bones_game` is also implicitly gated by assets loaded. I only check one `run_if` condition to avoid overhead executing systems that make up the core game loop.~~
=> fix: Fix race condition on if EguiCtx is initialized before bones game

framework_crates/bones_framework/src/networking.rs, framework_crates/bones_framework/src/networking/proto.rs
When GGRS sends predicted input on first frame (no prev input to use), it [zeroes PlayerInput](https://github.com/gschup/ggrs/blob/0af1a044b96465bd10398947b7fb5e0a34a75f70/src/frame_info.rs#L56) and uses that.
Due to how we quantize move direction, zeroed bits did not represent no movement input, it instead was `(-1.0, -1.0)`. This sometimes caused desync on beginning of online match.
Previously used 6 bit representation over range, was changed to quantize [0, 1.0] with 5 bits, and include a sign bit to map from [0, 1.0] -> [-1.0, 1.0]. Because range is symmetric and we quantize only half of it with one less bit, should still be same amount of precision. Now all zero bits represents 0 which is compatible with ggrs.
Additionally added debug log (not enabled by default) in networking to …
=> fix: Fix Zero'd DenseMoveDir not representing no input.

Cargo.lock, framework_crates/bones_framework/Cargo.toml
Switching to fork of ggrs with some fixes I am testing for desync. Desync occurs when client receives a frame it should rollback and correct while also at max prediction threshold (requires 3+ clients to hit failure, as if only 2 after receiving remote input 2nd would not be at max prediction anymore).
Changes being used are here: https://github.com/MaxCWhitehead/ggrs/tree/prediction-error-rollback-test
So far I no longer reproduce desync in jumpy, and the test I implemented in that branch is now passing.
=> fix(networking): Switch to ggrs fork with fix for corrections dropped at max prediction

framework_crates/bones_lib/src/lib.rs
Add SessionCommands which may be inserted as shared resource. Runs after session execution, before the "after_session" GameSystems.
One thing I don't like about this is it only works as shared resource, if user does not insert shared resource, and tries to do ResMutInit, they run into trouble. Not sure what the best way to avoid that is.
=> feat: Add Session commands to modify sessions from game code

framework_crates/bones_framework/src/networking.rs, framework_crates/bones_framework/src/networking/lan.rs, framework_crates/bones_framework/src/networking/online.rs, framework_crates/bones_lib/src/lib.rs
These are changes in prep for map transition. Session runner now has a restart function. When game session is reset, network session runner can be restarted by re-initializing it and using existing socket with increment match id. 
Sockets now wrap ggrs messages with a match_id that allows filtering in flight messages from previous matches out to avoid issues when re-creating ggrs session.
Note that GGRS takes a boxed socket - incrementing match id on our NetworkMatchSocket or other cloned socket will not impact current ggrs socket, which is fine as we are re-creating ggrs session anyway. It may only be effectively updated by cloning socket, incrementing, and re-creating ggrs session. This also avoids issues with interior mutability of NetworkMatchSocket (arc wrapping socket), so we …
=> feat(networking): Support restarting network session

framework_crates/bones_framework/src/networking.rs
Was passing in fps modified by net factor instead of original, so each restart of net session would incrementally lower fps.
=> fix(network): Fix net session runner restart lowering fps

Cargo.lock
=> chore(deps): Update rustls in Cargo.lock - resolve cargo deny advisory

framework_crates/bones_framework/src/networking.rs
Expose socket via `NetworkInfo` (resource managed by net session runner). 
`NetworkMatchSocket` resource only exists in menu session. This change makes it easier to get socket from game session. 
It might make sense to instead make this a shared resource and add Option so it may be default, however I worry about forgetting to clean this shared resource up when it is no longer relevant (If left multi-player game and went to single player and didn't clear shared resource, we would start executing online paths of code).
=> feat: Add socket to NetworkInfo

framework_crates/bones_bevy_renderer/src/lib.rs
Using borderless fullscreen mode fixes alt tab not working in fullscreen. Probably should support both - but this seems like a preferable default.
One side effect I see in jumpy is that when fullscreen on high res display the UI scaling no longer gets tiny (now looks as I'd expect). I'd show screenshots to compare, but the screenshot tool on macOS doesn't work in true fullscreen mode either 😉 
Any concerns with this?
=> fix: Use BorderlessFullscreen instead of true fullscreen (fix alt+tab)

other_crates/bones_matchmaker/src/cli.rs, other_crates/bones_matchmaker/src/lib.rs
Key can be passed in via `BONES_MATCHMAKER_SECRET_KEY`
To show the secret key when generating, you can pass `--print-secret-key` to the binary now
Closes #405
=> feat: add option to supply fixed secret key to the matchmaker

Cargo.lock
looks like time crate needed an update, CI  for minimal versions was failing. Will see if this fixes.
=> chore(deps):  update cargo.lock - fix minimal version CI

framework_crates/bones_framework/src/networking.rs
Each frame `DisconnectedPlayers` resource is updated in net session, can be used by game to determine which players may not be connected.
If rollback before a disconnect - player is still listed in resource, because dc'd players are persisted on runner directly + copied to resource.
=> feat(networking): Add 'DisconnectedPlayers' resource to net session runner

framework_crates/bones_framework/src/networking.rs, framework_crates/bones_lib/src/lib.rs
Add SessionRunner trait API for disabling local input. The use case for this is that in Jumpy when pausing the game in networked play, we do not want to set net game session inactive, as network loop will stop running and we will timeout. Instead can allow it to continue simulating and disable local input instead as a "pause".
=> feat: Allow local input to be disabled on SessionRunner.

framework_crates/bones_asset/src/server.rs
Small improvement found by my bro @tekhnaeraav.
=> refactor: remove unnecessary allocation when handling asset changes.

framework_crates/bones_ecs/src/resources.rs, framework_crates/bones_lib/src/lib.rs
Submitting on behalf of @TekhnaeRaav.
This makes it easier to track panic messages originating from calls to these functions.
=> fix: add missing track_callers for world.resource().

framework_crates/bones_ecs/src/entities.rs
Submitting on behalf of @tekhnaeraav:
Minor tweak that allows you use untyped component stores in `entities.iter_with()`.
=> feat: Impl `QueryItem` for `UntypedComponentStore`.

framework_crates/bones_framework/src/networking.rs, framework_crates/bones_framework/src/networking/lan.rs, framework_crates/bones_framework/src/networking/online.rs, framework_crates/bones_framework/src/networking/socket.rs, other_crates/bones_matchmaker/examples/matchmaker_client.rs, other_crates/bones_matchmaker/src/matchmaker.rs, other_crates/bones_matchmaker_proto/src/lib.rs
Naive pass at removing the max player limit. I haven't thought all parts through, but putting this here for a first round of feedback.
Closes #298
=> feat: remove MAX_PLAYER limit for networked games

framework_crates/bones_ecs/src/components/iterator.rs, framework_crates/bones_ecs/src/components/typed.rs, framework_crates/bones_ecs/src/components/untyped.rs, framework_crates/bones_ecs/src/entities.rs
Closes #289.
- Add `Entities::(get_)single_with` methods to get a single entity by a query
- Add `Entities::(get_)first_with_bitset` methods to get the first entity in the given bitset
- Add `Entities::(get_)first_with` methods to get the first entity in the given query
Add convenience methods to get a single entity (and optionally its components) when there should only be one of the thing you're looking for. This could be useful, for example, to check if there is only one player alive in the game. You could use `Entities::get_single_with` which would allow you to detect when there is only one player (`Ok`) or when there are none/multiple (`Err`).
All methods have a panicking and non-panicking variant -- e.g. `get_single_with` returns a `Result<_, QuerySingleError>`, while `single_with` …
=> feat: single & first entity queries

framework_crates/bones_asset/Cargo.toml, framework_crates/bones_asset/src/cid.rs, framework_crates/bones_asset/src/server.rs
With feature flag, during asset load, each input used to update cid are tracked and then logged.
One issue is that for dep_cid, I tried to get the AssetLoc for deps, but it appears to be None. Would be good to improve with some identifying information on dependency, right now just logs dep_cid and asset cid after update. If dep_cid differs, hard to tell which it is / why.
Dump for each asset is a single trace call, which hopefully will avoid any interleaved output as this runs in parallel for multiple assets.
Sample output:
```
2024-07-11T01:45:13.558171Z  INFO bones_asset::server: Cid trace schema: u!("jumpy::GameMeta") file path: "/game.yaml"
Trace is in order of updates, which impacts result
[Intermediate] Cid from schema fullname: u!("jumpy::GameMeta") cid: …
```
=> feat(assets): Add feature flag `cid_debug_trace` to bones_asset

Cargo.lock, framework_crates/bones_framework/Cargo.toml
There was some kind of semver-incompatible update to `ttf-parser` or a dependency or something that caused it to fail to compile after running a `cargo update` or starting a new Bones project with a fresh `Cargo.lock` file.
This updates `ttf-parser` to the latest version which fixes the error.
=> fix: update ttf-parser dependency to fix build error when starting with fresh lock file.

framework_crates/bones_asset/src/lib.rs
Exposed option methods directly on Maybe for less verbosity when using a lot of Maybes.
=> feat: add more helper methods on the `Maybe` type.

framework_crates/bones_bevy_renderer/src/lib.rs
Disable MSAA when in pixel art mode. It seems to add artifacts with texture sampling. Example: https://github.com/fishfolk/jumpy/issues/1014
=> fix: Disable MSAA in pixel art mode

framework_crates/bones_asset/src/lib.rs, framework_crates/bones_ecs/macros/core/src/lib.rs
The change allows using the bones_ecs crate SystemParam macro (under feature flag "derive") without bones_framework dependency, which I believe is unintendedly required at the moment.
=> fix: changed SystemParam derive macro to use ::bones_ecs instead of ::bones_framework

Cargo.lock, framework_crates/bones_framework/Cargo.toml, other_crates/bones_matchmaker/Cargo.toml, other_crates/bones_matchmaker_proto/Cargo.toml
0.21 has some bugs that completely breaks compiling on some set of systems. Bumping to 0.22 to address this.
Seems to compile/2 players connected on a quick test.
=> chore: bump iroh-net from 0.21 to 0.22

framework_crates/bones_schema/src/alloc/vec.rs
Adds a few more methods to SVec and also supports .into() SVec <-> Vec now both ways.
=> feat: Extend SVec with more methods 

framework_crates/bones_schema/src/alloc/resizable.rs, framework_crates/bones_schema/src/alloc/vec.rs
Fixes a mistake regarding the behavior of `copy_from_nonoverlapping()`. When copying from a typed pointer, we provide the number items to copy, not the number of bytes.
=> fix: fix undefined behavior in `SVec::pop()`.

framework_crates/bones_bevy_renderer/src/input.rs, framework_crates/bones_bevy_renderer/src/lib.rs, framework_crates/bones_bevy_renderer/src/rumble.rs, framework_crates/bones_framework/src/input/gamepad.rs
Added support for gamepad rumble into bones. Changed the interface compared to bevy's implementation with:
- Imo more straightforward naming/hiding abstractions like "requests"
- implementing an enable/disable layer which makes it easier for games to fully turn off rumble for a given gamepad without having to include `if` statements across their entire code (ie. during startup game can read from settings that gamepad X has rumble disabled, just call .disable(), and write code that always tries to use rumble without extra boilerplate).
=> feat: Adding rumble support

Cargo.lock, framework_crates/bones_ecs/Cargo.toml, framework_crates/bones_ecs/src/bitset.rs, framework_crates/bones_ecs/src/entities.rs
There were existing of `#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]` lines already (f.e. on Entity struct), but serde feature flag itself was missing from bones_ecs.
Also added `cfg_attr(feature = "serde") ...` line to Entities and BitSetVec so Entities struct can be serialized.
=> feat: added "serde" feature flag for bones_ecs

framework_crates/bones_framework/Cargo.toml, framework_crates/bones_framework/src/debug.rs, framework_crates/bones_framework/src/lib.rs, framework_crates/bones_framework/src/networking.rs, framework_crates/bones_framework/src/networking/debug.rs, framework_crates/bones_framework/src/render.rs
Locked some debug window that uses egui behind ui flag, fixed missing audio/ui cfg blocks in a few places.
The network debug system is now behind `net-debug`. This way it is not compiled if undesired, as it depends on 'ui' and is only useful if displayed in egui. Also probably something we will want to disable in release builds in the future.
Fixes #442
=> fix!: `bones_framework` not compiling with --no-default-features + net debug window behind feature flag `net-debug` (BREAKING)

framework_crates/bones_bevy_renderer/src/lib.rs
Tried turning it off to reduce some artifacts but I think this it is worse without it, maybe some other AA would work better, but not going to worry about this for now.
=> fix: re-enable msaa for pixel art mode

Cargo.lock, framework_crates/bones_framework/Cargo.toml, framework_crates/bones_framework/src/audio.rs, framework_crates/bones_framework/src/audio/audio_center.rs, framework_crates/bones_framework/src/audio/audio_manager.rs, framework_crates/bones_framework/src/lib.rs, framework_crates/bones_framework/src/render.rs, framework_crates/bones_framework/src/render/audio.rs
Moved AudioCenter out of jumpy -> bones.
Reworked to remove the dependency on using a game's settings struct directly + streamlining the interfaces such as having both play_sound and play_music be super easy to use, with extra _advanced and _custom methods for different levels of advanced features/usability on music.
Tested both music/sounds work.
=> feat: Integrating AudioCenter into bones

framework_crates/bones_framework/src/networking.rs
This PR covers the following:
1. Exposing player networking info from ggrs -> into an accessible resource for anyone to use.
2. Provide a bunch of helper methods for easily fetching averages/highest/lowest from networking info.
3. Convert `NetworkingInfo` struct to `SyncingInfo` (as discussed previously on discord) which supports both Online/Offline variants and put all fields behind getters. This will allow us to have a standardized interface for implementing EventManager in the future that watches current/last confirmed frame. (Of note this hasn't inserted the offline variant anywhere, as that can wait for the EventManager work itself).
=> feat: Added player networking info + preparation for future EventManager work

framework_crates/bones_ecs/src/stage.rs, framework_crates/bones_ecs/src/world.rs, framework_crates/bones_framework/src/networking.rs, framework_crates/bones_lib/src/lib.rs
This PR includes:
- Implementing a "single success system" flow, which allows a user to write a system that keeps trying to run every frame until it succeeds. This is handy for a bunch of use cases that were less friendly to write as always-on systems. Implemented with output `Option<()>` type to allow for users to take advantage of `?` when calling various getter methods.
- Adds easier access to components from `World`
- Adds methods for removing all systems, providing more flexibility of managing a session from within it
=> feat: Single success systems + helpers

framework_crates/bones_framework/src/audio/audio_center.rs
Implemented stop music/sound methods after I realized I couldn't stop the music in my game. Also added options to fade out with two separate custom fade out durations (one for music, and one for sounds).
=> feat: Adding missing stop interface for audio

framework_crates/bones_ecs/src/components/typed.rs
It was just an oversight that it wasn't already derived, because the inner untyped store is already `Clone`.
=> feat: derive `Clone` for `ComponentStore`.

framework_crates/bones_schema/macros/src/lib.rs, framework_crates/bones_schema/src/lib.rs
There was a bug in the `HasSchema` derive macro for generic types, where the enum variant schema was returning the schema for a previously computed instantiation of the generic type, instead of specializing based on the Rust type ID.
This fixes that, fixing undefined behavior that may be triggered when using `Maybe<T>` along with any other generic enums that have derived `HasSchema`.
This should also fix #296, which I can't reproduce right now, but could have been caused randomly by `Maybe::schema()` being unsound.
Fixes: #296
=> fix(soundness): fix a soundness bug with the `Maybe<T>` type and the `HasSchema` derive macro for generic types.

framework_crates/bones_schema/macros/src/lib.rs
Adds expanded docs by @TekhnaeRaav for the `HasSchema` derive macro.
=> docs: improve docs for the `HasSchema` derive macro.

Cargo.lock, demos/assets_minimal/src/main.rs, demos/features/src/main.rs, demos/hello_world/src/main.rs, demos/scripting/src/main.rs, framework_crates/bones_bevy_renderer/src/lib.rs, framework_crates/bones_framework/Cargo.toml, framework_crates/bones_framework/src/lib.rs, framework_crates/bones_framework/src/logging.rs
Implement LogPlugin in bones based off Bevy's LogPlugin. 
Shouldn't be much of a change in behavior, just 1st step in adding additional log functionality in bones, such as saving game log files to disk. 
One difference is that it no longer includes the `tracing_error` crate layer, I will review how this is used in bevy and see if we want to add this dependency. Want to make sure not going to degrade in error reporting quality for errors originating in bevy. (Plus maybe there is something can learn from this / use in bones). Context: https://github.com/bevyengine/bevy/blob/3cf70ba4f9d62396240b186ff379d27a312d2aa2/crates/bevy_log/src/lib.rs#L205
Logging is behind a feature flag, enabled by default. May be removed if user wants their own global subscriber configured.
=> feat(logging)!: Move logging setup to `setup_logging`, disable bevy LogPlugin, add logging to file system

framework_crates/bones_ecs/src/components/iterator.rs, framework_crates/bones_ecs/src/components/typed.rs, framework_crates/bones_ecs/src/components/untyped.rs, framework_crates/bones_ecs/src/entities.rs
Closes #289
Hello :wave: it's been a long while. This is take 2 of #386 which was reverted in cfce040 due to CI failures.
- Add `Entities::(get_)single_with` methods to get a single entity by a query
- Add `Entities::(get_)first_with_bitset` methods to get the first entity in the given bitset
- Add `Entities::(get_)first_with` methods to get the first entity in the given query
Add convenience methods to get a single entity (and one or more of its components) when there should only be one of the thing you're looking for. This could be useful, for example, to check if there is only one player alive in the game. You could use `Entities::get_single_with` which would allow you to detect when there is only one player (`Ok`) or when there are none/multiple (`Err`).
All methods have a panicking …
=> feat: single & first entity queries (take 2)

.github/miri-test.sh, .github/workflows/ci.yml, Cargo.toml, framework_crates/bones_ecs/Cargo.toml, framework_crates/bones_ecs/src/bitset.rs, framework_crates/bones_ecs/src/components/iterator.rs, framework_crates/bones_ecs/src/components/typed.rs, framework_crates/bones_ecs/src/components/untyped.rs, framework_crates/bones_ecs/src/entities.rs, framework_crates/bones_ecs/src/world.rs, framework_crates/bones_framework/src/logging.rs, framework_crates/bones_framework/src/time/timer.rs, framework_crates/bones_schema/src/alloc/map.rs
Closes #466 
- Fix: Bitsets are now correctly-sized (were x8 larger than expected)
- Fix: Unexpected panic when calling `Entities::create()` with a maxed-out bitset
- Fix: Reduce Miri CI job runtime to <30 minutes
- Fix: Warnings emitted by Miri
- Fix: Update the workspace `rust-version` to match the `rust-toolchain.toml` file at 1.81
- Add: More bitset iterator tests (there will be a follow-up PR on this to organize them and simplify some that involve `Entities` unnecessarily)
- Fix: Simplify test data, remove prints & `dbg!`s
**Fix: Bitsets are now correctly-sized (were x8 larger than expected)**
- Bitsets are `2^K` bits, and the number of `u32` arrays within them (which the docs now call "sectors") was previously calculated as `2^K / (32 * 8 / 8)`. The arrays are `32 * 8` bits meaning …
=> fix(miri): slow tests & bitset sizes

framework_crates/bones_ecs/src/components/iterator.rs, framework_crates/bones_ecs/src/components/typed.rs, framework_crates/bones_ecs/src/entities.rs, framework_crates/bones_schema/tests/tests.rs
Follow-up on #468.
*This PR makes changes exclusively within `*::tests` modules, there are no changes to lib code.*
- Move tests out of the `entities` module that don't belong
- Add more edge cases to help capture the similar but very different logic for all of the ways you can iterate component stores & bitsets
=> fix: reorganize ECS tests

Cargo.lock, framework_crates/bones_framework/Cargo.toml, framework_crates/bones_framework/src/networking.rs, framework_crates/bones_framework/src/networking/random.rs
This PR focused on finally linking the random seed generated by the matchmaker (pushing it to client was implemented in previous PR) into the GgrsSessionRunner + SyncingInfo, and then using it to create and insert a `RngGenerator` resource automatically for the developer to use easily.
Additionally, I created reworked the previous flow, now having a new interface that both re-wraps all of the Turborand methods (a few functions were inconsistent naming-wise, and gives us more flexibility to change stuff in the future), and also implements a number of missing functionality that will be helpful to devs. This new `RngGenerator` struct now supports:
1. Basic Number Generation: Methods for integers, floats, and booleans.
2. Range-based Generation: Methods for numbers within specified ranges.
3. …
=> feat: RNG Generator in bones

Cargo.lock, framework_crates/bones_bevy_renderer/Cargo.toml, framework_crates/bones_bevy_renderer/src/input.rs, framework_crates/bones_framework/Cargo.toml, framework_crates/bones_framework/src/input.rs, framework_crates/bones_framework/src/input/gilrs.rs
Replaces being tied to bevy for gamepad support (which is on an old version). Directly imports and orchestrates Gilrs in bones itself, while fitting into the existing input flow to not cause any issues until keyboard/mouse are also brought into bones.
=> feat: Direct Gilrs integration

framework_crates/bones_framework/src/input/gilrs.rs
I don't think we want SendWrapper here - this will panic if accessed from a different thread than it was initialized with, was panicking on start updating bones in jumpy. Bevy systems may be scheduled to other threads.
Arc + Mutex should make us sync + send here anyway. Lmk if any concerns with this @RockasMockas
=> fix(input): Remove SendWrapper from GILRS_CONTEXT (unless on wasm)

framework_crates/bones_framework/src/input/gamepad.rs, framework_crates/bones_framework/src/input/keyboard.rs
Very straightforward changes.
While working on [jumpy #933](https://github.com/fishfolk/jumpy/issues/933) I realized some of these events don't `impl Copy`.
=> feat(framework): make sure input structs `impl Copy`

.github/miri-test.sh, .github/workflows/pull-requests.yml, framework_crates/bones_framework/tests/system_param.rs
The new system param integration tests added in #482 [fail in miri](https://github.com/fishfolk/bones/actions/runs/11285906933/job/31389426144) due to features unavailable in isolation mode. Disable those tests since there isn't a good way to fix this.
=> fix: disable system param tests in miri

framework_crates/bones_framework/src/networking/lan.rs
Fixes #485.
Limit iroh node direct addresses to only IPv4 in attempt to keep the total property length under 256 bytes.
=> fix(lan): panic due to too-long mdns-sd property

framework_crates/bones_framework/src/networking.rs, framework_crates/bones_framework/src/networking/lan.rs
Also re-exports the `iroh` crate in the networking module.
=> refactor!: add configurable service for LAN matchmaking and fix bug when stopping hosting.
